# AsgDatabase Configuration

# Database settings
database:
  # The name of the database file (without extension)
  filename: players
  # Whether to backup the database on server shutdown
  backup-on-shutdown: true
  # Maximum number of backups to keep
  max-backups: 5

# Debug settings
debug:
  # Whether to enable debug logging
  enabled: false
  # Log database queries
  log-queries: false

# Performance settings
performance:
  # Maximum number of connections to the database
  max-connections: 10
  # Connection timeout in milliseconds
  connection-timeout: 30000
  # Whether to use connection pooling
  use-connection-pool: true

# API settings
api:
  # Whether to register the API as a service
  register-service: true
  # Service priority (Lowest, Low, Normal, High, Highest)
  service-priority: Normal